#!/usr/bin/env sh
set -eu

ROOT_DIR=${APP_ROOT:-/app}
cd "$ROOT_DIR"

if [ -f "$ROOT_DIR/router.env.sh" ]; then
  # shellcheck disable=SC1091
  . "$ROOT_DIR/router.env.sh"
fi

ROUTER_DATA_DIR=${ROUTER_DATA_DIR:-"$ROOT_DIR/.router-data"}
ROUTER_PROJECT_NAME=${ROUTER_PROJECT_NAME:-test}
ROUTER_CC_CONNECT_CMD=${ROUTER_CC_CONNECT_CMD:-cc-connect}
ROUTER_CACHE_DIR=${ROUTER_CACHE_DIR:-"$ROUTER_DATA_DIR/.cc-router-cache"}
ROUTE_CONFIG=${ROUTER_ROUTE_CONFIG_FILE:-"$ROUTER_DATA_DIR/config.route.toml"}
SETUP_CONFIG=${ROUTER_WEIXIN_SETUP_CONFIG:-"$ROUTER_DATA_DIR/.weixin-setup.toml"}
QR_IMAGE=${ROUTER_WEIXIN_QR_IMAGE:-"$ROUTER_DATA_DIR/weixin-qr.png"}
LOCAL_ENV=${ROUTER_LOCAL_ENV_FILE:-"$ROUTER_DATA_DIR/router.env.local.sh"}
WEIXIN_SETUP_TIMEOUT=${WEIXIN_SETUP_TIMEOUT:-600}

export ROUTER_DATA_DIR ROUTER_PROJECT_NAME ROUTER_CC_CONNECT_CMD ROUTER_CACHE_DIR
mkdir -p "$ROUTER_DATA_DIR" "$ROUTER_CACHE_DIR"

quote_shell() {
  printf "'"
  printf "%s" "$1" | sed "s/'/'\\\\''/g"
  printf "'"
}

default_env_line() {
  key=$1
  value=$2
  printf 'if [ -z "${%s:-}" ]; then export %s=%s; fi\n' "$key" "$key" "$(quote_shell "$value")"
}

write_local_env() {
  {
    echo "# Generated by docker-entrypoint.sh. Keep this file out of Git."
    for key in \
      WEIXIN_TOKEN \
      WEIXIN_ALLOW_FROM \
      WEIXIN_ADMIN_FROM \
      WEIXIN_ACCOUNT_ID \
      WEIXIN_CDN_BASE_URL \
      OPENAI_API_KEY \
      ROUTER_IMAGE_API_KEY \
      ROUTER_IMAGE_ENDPOINT \
      ROUTER_IMAGE_PROVIDER \
      ROUTER_IMAGE_MODEL \
      ROUTER_IMAGE_API \
      ROUTER_IMAGE_SIZE \
      ROUTER_IMAGE_QUALITY \
      ROUTER_IMAGE_CONTEXT_TTL_MINS \
      ROUTER_IMAGE_CONTEXT_MAX \
      ROUTER_CODE_API_KEY \
      ROUTER_CODE_ENDPOINT \
      ROUTER_CODE_PROVIDER \
      ROUTER_CODE_MODEL \
      ROUTER_CODE_TEMPERATURE \
      ROUTER_CODE_MAX_OUTPUT_TOKENS \
      ROUTER_CODE_REASONING_EFFORT
    do
      eval "value=\${$key:-}"
      default_env_line "$key" "$value"
    done
  } > "$LOCAL_ENV"
}

toml_string() {
  node -e 'process.stdout.write(JSON.stringify(String(process.argv[1]).replace(/\\/g, "/")))' "$1"
}

write_setup_config() {
  toml_data_dir=$(toml_string "$ROUTER_DATA_DIR")
  toml_root=$(toml_string "$ROOT_DIR")
  toml_project=$(toml_string "$ROUTER_PROJECT_NAME")
  toml_cmd=$(toml_string "sh $ROOT_DIR/router.route.sh")

  cat > "$SETUP_CONFIG" <<EOF
language = "zh"
data_dir = $toml_data_dir

[log]
level = "info"

[[projects]]
name = $toml_project
show_context_indicator = false
reply_footer = false

[projects.agent]
type = "codex"

[projects.agent.options]
work_dir = $toml_root
mode = "full-auto"
cmd = $toml_cmd
EOF
}

write_route_config() {
  toml_data_dir=$(toml_string "$ROUTER_DATA_DIR")
  toml_root=$(toml_string "$ROOT_DIR")
  toml_project=$(toml_string "$ROUTER_PROJECT_NAME")
  toml_route_cmd=$(toml_string "sh $ROOT_DIR/router.route.sh")
  toml_control_cmd=$(toml_string "sh $ROOT_DIR/router.control.sh {{args:status}}")

  cat > "$ROUTE_CONFIG" <<EOF
language = "zh"
data_dir = $toml_data_dir

[log]
level = "info"

[[projects]]
name = $toml_project
admin_from = "\${WEIXIN_ADMIN_FROM}"
show_context_indicator = false
reply_footer = false

[projects.agent]
type = "codex"

[projects.agent.options]
work_dir = $toml_root
mode = "full-auto"
cmd = $toml_route_cmd

[[projects.platforms]]
type = "weixin"

[projects.platforms.options]
token = "\${WEIXIN_TOKEN}"
allow_from = "\${WEIXIN_ALLOW_FROM}"
account_id = "\${WEIXIN_ACCOUNT_ID}"
base_url = "https://ilinkai.weixin.qq.com"
cdn_base_url = "\${WEIXIN_CDN_BASE_URL}"
proxy = ""

[[commands]]
name = "route"
description = "Show or switch the smart routing mode / \u67e5\u770b\u6216\u5207\u6362\u667a\u80fd\u8def\u7531\u6a21\u5f0f"
exec = $toml_control_cmd

[[aliases]]
name = "\u5f53\u524d\u6a21\u5f0f"
command = "/route status"

[[aliases]]
name = "\u56fe\u7247\u6a21\u5f0f"
command = "/route image"

[[aliases]]
name = "\u56fe\u50cf\u6a21\u5f0f"
command = "/route image"

[[aliases]]
name = "\u751f\u56fe\u6a21\u5f0f"
command = "/route image"

[[aliases]]
name = "\u751f\u6210\u56fe\u7247\u6a21\u5f0f"
command = "/route image"

[[aliases]]
name = "\u7ed8\u56fe\u6a21\u5f0f"
command = "/route image"

[[aliases]]
name = "\u753b\u56fe\u6a21\u5f0f"
command = "/route image"

[[aliases]]
name = "\u4ee3\u7801\u6a21\u5f0f"
command = "/route code"

[[aliases]]
name = "\u95ee\u7b54\u6a21\u5f0f"
command = "/route code"

[[aliases]]
name = "\u901a\u7528\u95ee\u7b54\u6a21\u5f0f"
command = "/route code"

[[aliases]]
name = "\u81ea\u52a8\u6a21\u5f0f"
command = "/route auto"

[[aliases]]
name = "\u667a\u80fd\u6a21\u5f0f"
command = "/route auto"

[[aliases]]
name = "\u667a\u80fd\u8def\u7531"
command = "/route auto"
EOF
}

extract_toml_value() {
  node - "$1" "$2" <<'NODE'
const fs = require("fs");
const file = process.argv[2];
const key = process.argv[3];
let text = "";
try {
  text = fs.readFileSync(file, "utf8");
} catch {
  process.exit(0);
}
const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const match = text.match(new RegExp(`(?:^|\\n)\\s*${escapedKey}\\s*=\\s*"([^"]*)"`));
if (match && match[1] && !match[1].startsWith("${")) {
  process.stdout.write(match[1]);
}
NODE
}

extract_weixin_token_from_data() {
  node - "$ROUTER_DATA_DIR" <<'NODE'
const fs = require("fs");
const path = require("path");
const root = path.join(process.argv[2], "weixin");
const files = [];

function walk(dir) {
  let entries = [];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(fullPath);
    } else if (entry.name === "get_updates.buf") {
      try {
        files.push({ fullPath, mtimeMs: fs.statSync(fullPath).mtimeMs });
      } catch {
      }
    }
  }
}

walk(root);
files.sort((a, b) => b.mtimeMs - a.mtimeMs);

for (const file of files) {
  try {
    const raw = fs.readFileSync(file.fullPath, "utf8").trim();
    if (!raw) continue;
    const decoded = Buffer.from(raw, "base64").toString("utf8");
    const match = decoded.match(/([A-Za-z0-9._-]+@im\.[A-Za-z0-9.-]+:[A-Za-z0-9]+)/);
    if (match) {
      process.stdout.write(match[1]);
      process.exit(0);
    }
  } catch {
  }
}
NODE
}

extract_weixin_admin_from_data() {
  node - "$ROUTER_DATA_DIR" <<'NODE'
const fs = require("fs");
const path = require("path");
const root = process.argv[2];
const files = [];
const userRe = /([A-Za-z0-9._-]+@im\.wechat)/;

function walk(dir) {
  let entries = [];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(fullPath);
    } else if (entry.name === "context_tokens.json" || fullPath.includes(`${path.sep}sessions${path.sep}`)) {
      try {
        files.push({ fullPath, mtimeMs: fs.statSync(fullPath).mtimeMs });
      } catch {
      }
    }
  }
}

walk(root);
files.sort((a, b) => b.mtimeMs - a.mtimeMs);

for (const file of files) {
  try {
    const text = fs.readFileSync(file.fullPath, "utf8");
    const match = text.match(userRe);
    if (match) {
      process.stdout.write(match[1]);
      process.exit(0);
    }
  } catch {
  }
}
NODE
}

ensure_account_values() {
  if [ -z "${WEIXIN_ALLOW_FROM:-}" ]; then
    WEIXIN_ALLOW_FROM='*'
    export WEIXIN_ALLOW_FROM
  fi

  if [ -z "${WEIXIN_CDN_BASE_URL:-}" ]; then
    WEIXIN_CDN_BASE_URL='https://novac2c.cdn.weixin.qq.com/c2c'
    export WEIXIN_CDN_BASE_URL
  fi

  if [ -z "${WEIXIN_ACCOUNT_ID:-}" ] && [ -n "${WEIXIN_TOKEN:-}" ]; then
    WEIXIN_ACCOUNT_ID=${WEIXIN_TOKEN%%:*}
    export WEIXIN_ACCOUNT_ID
  fi
}

validate_api_env() {
  missing=""

  if [ -z "${ROUTER_IMAGE_API_KEY:-}" ] && [ -z "${OPENAI_API_KEY:-}" ]; then
    missing="$missing ROUTER_IMAGE_API_KEY-or-OPENAI_API_KEY"
  fi
  if [ -z "${ROUTER_CODE_API_KEY:-}" ] && [ -z "${OPENAI_API_KEY:-}" ]; then
    missing="$missing ROUTER_CODE_API_KEY-or-OPENAI_API_KEY"
  fi
  case ${ROUTER_IMAGE_ENDPOINT:-} in
    ""|*your-api.example*) missing="$missing ROUTER_IMAGE_ENDPOINT" ;;
  esac
  case ${ROUTER_CODE_ENDPOINT:-} in
    ""|*your-api.example*) missing="$missing ROUTER_CODE_ENDPOINT" ;;
  esac

  if [ -n "$missing" ]; then
    echo "Missing required environment values:$missing" >&2
    echo "Copy .env.example to .env, fill it, then run: sh deploy.sh up" >&2
    return 1
  fi
}

run_weixin_setup() {
  command_name=setup
  if [ "${WEIXIN_FORCE_REBIND:-0}" = "1" ]; then
    command_name=new
    case "$ROUTER_DATA_DIR" in
      "$ROOT_DIR"/*) rm -rf "$ROUTER_DATA_DIR/weixin" ;;
      *) echo "Refusing to clear WEIXIN state outside APP_ROOT: $ROUTER_DATA_DIR" >&2 ;;
    esac
  fi

  rm -f "$QR_IMAGE" "$SETUP_CONFIG"
  write_setup_config

  echo "WEIXIN_TOKEN is empty. Starting Weixin QR setup..."
  echo "QR image will be saved to: $QR_IMAGE"
  echo "Open that file from the Mac host and scan it with Weixin."

  set +e
  "$ROUTER_CC_CONNECT_CMD" weixin "$command_name" \
    --config "$SETUP_CONFIG" \
    --project "$ROUTER_PROJECT_NAME" \
    --qr-image "$QR_IMAGE" \
    --timeout "$WEIXIN_SETUP_TIMEOUT" \
    --set-allow-from-empty
  setup_status=$?
  set -e

  token=$(extract_toml_value "$SETUP_CONFIG" token || true)
  if [ -z "$token" ]; then
    token=$(extract_weixin_token_from_data || true)
  fi

  if [ -z "$token" ]; then
    echo "Weixin setup finished without a token. Send one Weixin message to the bot, then restart." >&2
    if [ "$setup_status" -eq 0 ]; then
      setup_status=1
    fi
    return "$setup_status"
  fi

  WEIXIN_TOKEN=$token
  export WEIXIN_TOKEN

  admin_from=$(extract_toml_value "$SETUP_CONFIG" admin_from || true)
  if [ -z "$admin_from" ]; then
    admin_from=$(extract_weixin_admin_from_data || true)
  fi
  if [ -n "$admin_from" ]; then
    WEIXIN_ADMIN_FROM=$admin_from
    export WEIXIN_ADMIN_FROM
  fi

  ensure_account_values
  write_local_env

  if [ "$setup_status" -ne 0 ]; then
    echo "Weixin setup exited with $setup_status, but token was saved. Continuing..."
  fi
}

start_router() {
  if ! validate_api_env; then
    exec tail -f /dev/null
  fi
  ensure_account_values

  if [ -z "${WEIXIN_TOKEN:-}" ] || [ "${WEIXIN_FORCE_REBIND:-0}" = "1" ]; then
    if ! run_weixin_setup; then
      exec tail -f /dev/null
    fi
  fi

  ensure_account_values
  write_local_env
  write_route_config

  echo "Starting cc-connect route service..."
  echo "Config: $ROUTE_CONFIG"
  echo "Data:   $ROUTER_DATA_DIR"
  exec "$ROUTER_CC_CONNECT_CMD" --config "$ROUTE_CONFIG" --force
}

case "${1:-start}" in
  start)
    start_router
    ;;
  setup)
    validate_api_env
    ensure_account_values
    run_weixin_setup
    ;;
  sh|shell)
    exec sh
    ;;
  *)
    exec "$@"
    ;;
esac
